.PHONY : all clean

all : book.pdf

clean :
	latexmk -C

book.pdf: book.tex body.tex markdown_date.tex
	latexmk -pdf book.tex

markdown_date.tex: book/.git/logs/HEAD
	echo "%%% This file is generated by Makefile." > markdown_date.tex
	echo "%%% Do not edit this file!\n%%%" >> markdown_date.tex
	cd book; git log -1 --format="format:\\gdef\\GitMarkdownDate{%ad}" >> ../markdown_date.tex
